#!/usr/bin/env bash

function main {
  local version="$(cat "${PLUGIN_VERSION}")"
  hub release delete "${version}" || true
  hub release create -a "${PLUGIN_FILE}" -m "${version}" "${version}"
}

main "$@"
